version: '2'
# 服务
services:
  phoenix:
    # 使用镜像
    image: nginx
    # 使用端口
    ports:
      - "8080:80"
    # 所属网络
    # 以下设置中 phoenix 能与 dragon & monkey Ping 通 
    networks: 
      - "fairyland"
      - "default"
    # phoenix & dragon 的 /mnt 是相同目录
    # phoenix & dragon 的 /usr/share/nginx/html 为 项目中的 ./app/web 目录
    volumes:
      - nest:/mnt
      - ./app/web:/usr/share/nginx/html
  dragon:
    image: nginx
    ports:
      - "8081:80"
    networks: 
      - "fairyland"
    volumes:
      - nest:/mnt
      - ./app/web:/usr/share/nginx/html
  monkey:
    image: nginx
    ports:
      - "8082:80"
    networks: 
      - "default"
# 网络
# 网络 default 会 自动添加
networks: 
  fairyland:
    driver: bridge
# 数据卷
volumes:
  nest:
    driver: local